#pragma once
#include "main.h"

#define PORT_OPTICAL 6
#define PORT_INERTIAL 7
#define PORT_ROTATION_HORIZONTAL -20
#define PORT_ROTATION_VERTICAL 21
#define PORT_ROTATION_LADYBROWN 15
#define PORT_DISTANCE 16

#define PORT_HOOKS (-5)
#define PORT_INTAKE 11

#define PORT_LADYBROWN 19

#define PORT_DRIVE_LEFT_FRONT (-8)  //reversed
#define PORT_DRIVE_LEFT_TOP (-9)
#define PORT_DRIVE_LEFT_BOTTOM (-10) //reversed
#define PORT_DRIVE_RIGHT_FRONT 1
#define PORT_DRIVE_RIGHT_TOP 2 //reversed
#define PORT_DRIVE_RIGHT_BOTTOM 3

#define PORT_ADI_LATCH_LEFT 'F'
#define PORT_ADI_LATCH_RIGHT 'B'
#define PORT_ADI_DOINKY 'C'
#define PORT_ADI_CLAW 'D'